# Generated by Django 3.0.5 on 2022-10-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainuser',
            name='phoneno',
            field=models.CharField(default=False, max_length=13),
        ),
        migrations.AddField(
            model_name='chainuser',
            name='user_address',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='chainuser',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chainuser',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chainuser',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chainuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chainuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
