# Generated by Django 3.0.5 on 2022-10-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_auto_20221012_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainuser',
            name='user_address',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
