# Generated by Django 3.0.5 on 2022-10-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_auto_20221012_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainuser',
            name='userimg',
            field=models.ImageField(default='', upload_to='User/images'),
        ),
        migrations.AlterField(
            model_name='chainuser',
            name='user_address',
            field=models.CharField(default=False, max_length=60),
        ),
    ]
