# Generated by Django 3.1.13 on 2022-11-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_auto_20221012_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainuser',
            name='user_kyc',
            field=models.CharField(default='', max_length=15),
        ),
    ]
