# Generated by Django 3.1.13 on 2022-11-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0007_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chainuser',
            old_name='is_admin',
            new_name='is_purchaser',
        ),
    ]
