# Generated by Django 3.1.13 on 2022-11-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0008_auto_20221113_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='veggies/images'),
        ),
    ]
